# AGY CLI profile (class agy-cli)
include kitty.conf

background_image /home/kodex/Pictures/Kdx/agy-bg.jpg
background_image_layout cscaled
background_tint 0.45
background_opacity 0.85
dynamic_background_opacity yes
background #120904
foreground #f5e8df
