enabled_layouts vertical,horizontal,stack

font_family      CaskaydiaCove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0
background #000000
background_image /home/kodex/Pictures/Kdx/Makima-dark.png
background_image_layout cscaled
# background_tint 0.5

allow_remote_control yes
shell_integration no-title
listen_on unix:/tmp/kitty-{kitty_pid}

# Splits heredan directorio actual
map ctrl+shift+enter no_op
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+- launch --location=hsplit --cwd=current
map ctrl+shift+\ launch --location=vsplit --cwd=current
map ctrl+shift+y launch --cwd=current /usr/bin/yazi

# Tabs
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         round
tab_title_template          " {index}: {tab.title if tab.title else title} "
active_tab_foreground       #f0e0e0
active_tab_background       #722f37
active_tab_font_style       bold
inactive_tab_foreground     #a6adc8
inactive_tab_background     #313244
inactive_tab_font_style     normal

# Desactivar confirmación de cierre al cerrar con comandos como exit
confirm_os_window_close 0
